import { Nunito } from "next/font/google";
import "./globals.css";
import Sessionwrapper from "./components/Sessionwrapper";
import 'izitoast/dist/css/iziToast.min.css';

const nunitoroi = Nunito({
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700","800", "900"],
  subsets: ["latin"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunitoroi.variable} antialiased`}
      >
        <Sessionwrapper>
        {children}
        </Sessionwrapper>
      </body>
    </html>
  );
}
